services:
  asistencia:
    image: node-asistencia
    container_name: node-asistencia
    build:
      context: .
    command: sh -c "npm start"
    ports:
      - 3333:3333
    networks:
      - redasistenciaAle

networks:
  redasistenciaAle:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.31.0/24"
          gateway: "192.168.31.1"
